/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,tsx,ts}"],
  darkMode: "class",
  plugins: [],
  theme: {
    extend: {
      colors: {
        primary: "rgba(var(--primary))",
        primaryDark: "rgba(var(--primaryDark))",
        primaryLight: "rgba(var(--primaryLight))",
        secondary: "rgba(var(--secondary))",
        secondaryDark: "rgba(var(--secondaryDark))",
        secondaryLight: "rgba(var(--secondaryLight))",
        green: "rgba(var(--green))",
        greenDark: "rgba(var(--greenDark))",
        greenLight: "rgba(var(--greenLight))",
        yellow: "rgba(var(--yellow))",
        yellowDark: "rgba(var(--yellowDark))",
        yellowLight: "rgba(var(--yellowLight))",
        red: "rgba(var(--red))",
        redDark: "rgba(var(--redDark))",
        redLight: "rgba(var(--redLight))",
        background: "rgba(var(--background))",
        card: "rgba(var(--card))",
        textPrimary: "rgba(var(--textPrimary))",
        textSecondary: "rgba(var(--textSecondary))",
        grey: "rgba(var(--grey))",
        greyLight: "rgba(var(--greyLight))",
        greyDark: "rgba(var(--greyDark))",
        icon: "rgba(var(--icon))",
        "gradient-textPrimary": "rgba(var(--gradient-textPrimary))",
        "gradient-textSecondary": "rgba(var(--gradient-textSecondary))",
        "bg-dark": "rgba(var(--bg-dark))",
        "bg-light": "rgba(var(--bg-light))",
      },
    },
  },
};
