export { createGame, type Game } from '~/game.js'
export * from '~/entity.js'
export * from '~/spawnable/args.js'
export * from '~/spawnable/definition.js'
export * from '~/spawnable/spawnableEntity.js'
export type { Physics } from '~/physics.js'
