name: Check Formatting
on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check formatting
        shell: bash
        run: deno task format:base --check .
